[paths]
factory_state_file = "/Users/zepu/Library/Application Support/factorio/script-output/factory_state.json"
log_file = "log_file.txt"

[mqtt]
broker = "supos-ce-instance1.supos.app"
port = 1883
topic_prefix = "Factorio/Sandbox"
username = ""
password = "" 